name = "Ferris"
uuid = "63f0097a-12ad-48b6-b958-b7ba3e438463"
authors = ["Oliver Wooding <oliverwooding@icloud.com>"]
version = "0.1.1"

[deps]
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
